### ISSUE TITLE
[REQ] Improvements to the `!map` command

### ISSUE THREAD

**Issue by crashzk** [daffyyyy/CS2-SimpleAdmin#10]
Would it be possible to implement the map change command for the CS2 default maps and the workshop maps in the same command?

Example, use the `!map` command for both maps such as `de_dust2`, `de_inferno` and for workshop maps, `ws:awp_india`

**Comment by crashzk** [comment]
News about this feature? It would be possible?

In this case, it would be migrating the two commands `!map` and `!wsmap` into the same command, `!map` for official and workshop servers.

**Comment by daffyyyy** [comment]
Done in commit https://github.com/daffyyyy/CS2-SimpleAdmin/commit/e028bef5b0983661fe4167386f62618eb9d740ae
