### ISSUE TITLE
A minor thing, I can't seem to get the commands to work with Binding keys i.e.    bind "F5" "say !css_admin"

### ISSUE THREAD

**Issue by Jano1959** [daffyyyy/CS2-SimpleAdmin#100]
A REAL minor thing! 

I can't seem to get the commands to work with Binding keys i.e.    bind "F5" "say !css_admin"

**Comment by daffyyyy** [comment]
csa_admin is a console command, not chat command

**Comment by Jano1959** [comment]
1st of all!  THANKS A LOT for your work here!

I would love to use bind to execute some commands, like getting the admin menu on screen. (old habit from SM in CSGO..)

Would it be possible in any way?

When I use bind "F5" "say !admin"    Is still does not work, but maybe that also is a console command.

**Comment by TsunaDev** [comment]
As it is a console command, you just have to put the command in the bind `bind "F5" css_admin`

**Comment by Jano1959** [comment]
Ahh, my error, thank you :)
