### ISSUE TITLE
how to add map list to !admin menu

### ISSUE THREAD

**Issue by mayersgamer** [daffyyyy/CS2-SimpleAdmin#101]
how to add default and workshop maps to the admin list menu

**Comment by Dliix66** [comment]
You add all in the config.

**Comment by mayersgamer** [comment]
which config ? give small exemple

**Comment by mayersgamer** [comment]
worshop maps shoudnt be the id of the map ?

**Comment by Dliix66** [comment]
Nop

**Comment by mayersgamer** [comment]
> Nop

hey man can you tell how to stop admins from muting and banning each other

**Comment by mayersgamer** [comment]
> Nop
> Admins can ban other admins that have the same immunity or less immunity than them.

hey  i tried to put workshop maps as you said by name , and they didnt change the map.

setting by worshop id works , but its hard to know which map im selecting tho because they are numbers instead of names.
