### ISSUE TITLE
Implement consistent targeting

### ISSUE THREAD

**Issue by dollannn** [daffyyyy/CS2-SimpleAdmin#102]
CSGO and sourcemod had a good targeting system, currently it is very inconsistent which commands use steamid, name or userid.

It would be beneficial for everyone if commands had a clear and concise way of targeting. Also something which annoys me is that certain commands such as ungag or unmute, removes the penalty for everyone with the name of "Adam" even though all those Adams might not be online, any type of removal of punishment by name should only be allowed for online players. Some commands could even be merged with this system as selectors define what route the command takes.

[Reference](https://wiki.alliedmods.net/Admin_Commands_(SourceMod))

**Comment by daffyyyy** [comment]
Just use steamid for offline player?

**Comment by dollannn** [comment]
Yes but the commands are differentiated. It would be best if there was some sort of way for the commands to recognize which selector is used either name, userid or steamid and execute based on that
