### ISSUE TITLE
Flags / Add Admin

### ISSUE THREAD

**Issue by romerocox** [daffyyyy/CS2-SimpleAdmin#108]
Can someone assist while adding an admin? 

I've tried:

css_addadmin "SafiraSkins" "id" 100 "abcdefghz" 0
css_addadmin "SafiraSkins" "id" 100 z 0

none of them works and I can't find find the right way to do it.

**Comment by mayersgamer** [comment]
/game/csgo/addons/counterstrikesharp/configs

admins.json

here is an example of my cfg 

https://pastebin.com/z1Y9ydTU

**Comment by romerocox** [comment]
Thanks, do you know if it’s possible to use the css_add admin command? 

> /game/csgo/addons/counterstrikesharp/configs
> 
> admins.json
> 
> here is an example of my cfg
> 
> https://pastebin.com/z1Y9ydTU

**Comment by daffyyyy** [comment]
Read command description and css flag system
