### ISSUE TITLE
Problem with change map (no list)

### ISSUE THREAD

**Issue by GrishaKosak** [daffyyyy/CS2-SimpleAdmin#114]
Hello, first of all thanks for your work.

I have a problem with changing the map via !admin.
I don't have a map list, I looked in the cfg files and the plugin channel, but I didn't find anything that would indicate where to enter the map list. Will you help?

![123123123](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/101899895/aaebf8ba-4869-4d7d-9a7c-ded0512b2e37)

**Comment by Zoulag0** [comment]
hey, i have same problem here.
I tryied many way to input maps names... nothing is working.
this is how i edit the CS2-SimpleAdmin.json file last time :

"DefaultMaps": ["cs_office",
  "cs_italy",
  "ar_baggage",
  "ar_shoots",
  "cs_orange",
  "de_ancient",
  "de_anubis",
  "de_dust2",
  "de_inferno",
  "de_mirage",
  "de_nuke",
  "de_overpass",
  "de_vertigo"],
  "WorkshopMaps": ["de_assembly",
  "de_biome",
  "de_breach",
  "de_cbble",
  "de_dust_hr",
  "de_foroglio",
  "de_inferno_night",
  "de_mills",
  "de_ravine",
  "de_thera",
  "de_tides_cs2",
  "de_vandal",
  "deathrun_playground",
  "fun_bounce",
  "fy_pool_day",
  "kz_igneous",
  "de_memento",
  "de_akiba",
  "aim_chill_maincity_zk",
  "de_brewery",
  "aim_map",
  "de_train",
  "aim_deagle7k"],

**Comment by GrishaKosak** [comment]
> 

thanks friend :) its working.
But now I had a freeze of server after change map :( maybe its problem with noaccual plugins after cs2 updates...

![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/101899895/cbf055de-4e86-4842-b4ef-b404c540f507)

**Comment by daffyyyy** [comment]
> > 
> 
> thanks friend :) its working.
> But now I had a freeze of server after change map :( maybe its problem with noaccual plugins after cs2 updates...
> 
> ![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/101899895/cbf055de-4e86-4842-b4ef-b404c540f507)
> 
> 

Yes, sometimes server can crash after map change (game problem or other plugin).
U can check if u use exact map name as map filename
