### ISSUE TITLE
can't hide chat commands

### ISSUE THREAD

**Issue by DJDMM** [daffyyyy/CS2-SimpleAdmin#116]
How can I hide chat [SA], everyone can see my commands! Only when I am on hide it's not showing. How can I cahnge it?

**Comment by mayersgamer** [comment]
try with language file addons/counterstrikesharp/plugins/CS2-SimpleAdmin/lang  en.json

**Comment by Mr-Robot-ops** [comment]
Core.json
`"PublicChatTrigger": [ "!" ],
`
`"SilentChatTrigger": [ "/" ],`
