### ISSUE TITLE
Problem with changing map

### ISSUE THREAD

**Issue by GrishaKosak** [daffyyyy/CS2-SimpleAdmin#118]
hey.
After changing map (manually) by !admin !2 etc
plugin crush server

I also using plugins:

CounterStrikeSharp https://github.com/roflmuffin/CounterStrikeSharp/releases
fake rcon https://github.com/Salvatore-Als/cs2-fake-rcon/releases
K4-System https://github.com/K4ryuu/K4-System/releases
MatchZy https://github.com/shobhit-pathak/MatchZy/releases

![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/101899895/f8876b72-2be1-4805-801b-044a2d46866f)

**Comment by daffyyyy** [comment]
Its not problem with plugin, i guess configuration or other plugins.

**Comment by GrishaKosak** [comment]
ayy, ok thanks.
Do U see somenthg strange in this screenshot ? Any advice ?
