### ISSUE TITLE
When user is gagged chat commands cannot be used (Re-opened)

### ISSUE THREAD

**Issue by shmitzas** [daffyyyy/CS2-SimpleAdmin#119]
Re-opening as this issue remains in the latest build (215) https://github.com/daffyyyy/CS2-SimpleAdmin/issues/76

**Comment by shmitzas** [comment]
by using this listener
`AddCommandListener(null, OnCommandGlobal);`
you can listen to any command it it works 😄 
For example to listen to "say" command you could use
`
private HookResult OnCommandGlobal(CCSPlayerController? player, CommandInfo info)
{
    if (info.ArgCount < 2)
        return HookResult.Continue;

    var command = info.GetArg(0);
    var message = info.GetArg(1);

    if (string.IsNullOrEmpty(command))
        return HookResult.Continue;
    switch (command)
	{
		case "say":
            break;
    }
}
`

**Comment by shmitzas** [comment]
And don't use `Server.ExecuteCommand($"css_tag_mute {playerInfo.SteamId}");` because that prevents user from typing not only regular texts in chat, but commands as well

**Comment by itsPoipoi** [comment]
Why not just type "css_ungag [your id]" in the console?
