### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by BMathers35** [daffyyyy/CS2-SimpleAdmin#12]
## !team command
The !team command allows players to switch teams without killing them, but this can sometimes be impractical. Therefore, if the !team command is used, the player(s) will be sent to the designated team after being killed. If it is necessary to change teams without killing the player(s), the !forceteam command will be used.

`@ct` => Players on the counter-terrorist team
`@t` => Players on the terrorist team
`@spec` => Players in the spectator
`@all` => All players on the server

### Example Usages
| Command | Description |
|--------|--------|
| `!team <@ct/@t>` | Sends the specified team to the other team. |
| `!team <@all>` | Sends both teams to the opposing team. |
| `!team <@all> <@t/@ct/@spec>` | Sends all players to the designated team. |
| `!team <@ct/@t/@spec> <@t/@ct/@spec>` |  Sends the specified team players to the designated team. |
| `!team <PlayerName>` | Sends the indicated player to the other team. | 
| `!team <PlayerName> <@t/@ct/@spec>` | Sends the indicated player to the designated team. |

In addition, it is useful to pay attention to incorrect usage in this command (For example: `!team @spec @spec` etc.)
If the same commands are used with !forceteam instead of !team, it will change the team without killing the player(s).

**Note:** It might make more sense if the name of the command is !swap and !forceswap instead of !team.

## !strip command
Removes all weapons held by a specific player or team.
| Command | Description |
|--------|--------|
| `!strip <@ct/@t/@all>` | Removes weapons from the hands of the specified team or everyone. |
| `!strip <PlayerName>` | Only removes weapons in the hands of the specified player. |

## !give/!hp/!god/!speed/!slay/!slap/!gag/!mute commands
Like the team, I think these commands need tags like @all/@t/@ct, because there may be situations where we need to treat a specific team or all players.

## !afk command
Allows the player to switch to the Spec team.

## Adjustable json support for console output commands
A setting for output in JSON format from the configuration file for !players, !who and similar commands.

**Comment by daffyyyy** [comment]
1. Done, command `css_team @all/@t/@ct/@all team` OPTIONAL `-k` or `css_team @all/@t/@ct/@all swap OPTIONAL -k`
2. Done, new command `css_strip`
3. Done earlier  
4. This is admin system, not afk manager

**Comment by daffyyyy** [comment]
Probably done in 1.2.3a?

**Comment by BMathers35** [comment]
Yes, everything seems to be working properly. Thank you very much. Additionally, @me tag can be added to commands, although it is not necessary. Although there is no jailbreak game mode at the moment, jailbreak admins usually use this tag a lot
