### ISSUE TITLE
Map config !

### ISSUE THREAD

**Issue by ddbmaster** [daffyyyy/CS2-SimpleAdmin#123]
Ask ! 
Where is the folder for Mapvotes, Workshop
and what should the file be called
Thanks in advance
Unfortunately I can't find that

![auswahl-map](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/13317545/f9d35756-4e58-4886-9e04-d9aa81d9b479)

![keie-map](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/13317545/9f5e9fdf-1354-4bf5-9bb4-89960144cfcb)

**Comment by t4r1k58** [comment]
config cs2-simpleadmin.json

  "DefaultMaps": ["de_dust2",
    "cs_italy",
    "cs_office",
    "de_ancient",
    "de_anubis",
    "de_inferno",
    "de_mirage",
    "de_nuke",
    "de_overpass",
    "de_vertigo"],

**Comment by ddbmaster** [comment]
Thx is okay

**Comment by ddbmaster** [comment]
But workshop maps don't work with names no result
  "WorkshopMaps": [
"fy_iceworld"],
Doesn't change the map
and when you enter the ID
  "WorkshopMaps": [
"3073470072"],
An error occurs and no maps are displayed anymore

manual via wsmap ID is OK
3070543311 Okay
 3070219079 Okay
 3099519038 Okay
 3133582456 Okay
 3079677245 Okay
 3083296922 Okay
 3203130178 Okay
 3109410513 Okay
 3202826456 Okay
 3120867158 Okay
 3070612859 Okay
 3071100532 Okay
 3070595459 Okay

Nanuel wsmap Name is Not Okay
e.g 
de_piranesi 
de_santo 
de_mirage 
de_tides_cs2 
de_aldebaran 
de_astra 
de_agreste_s2 
de_chateau_cs2 
de_ruins 
de_amalia 
de_shortdust 
de_alexandra 
de_dust 

Can you please help me, what am I doing wrong?

**Comment by S1ncer3ly** [comment]
same issue about workshop maps
like what to input ??

**Comment by daffyyyy** [comment]
Check workshop maps list

**Comment by ddbmaster** [comment]
Yes, okay, but where can I find the list?
and how is this entered into the list? Please provide an example

**Comment by tf-anguskong** [comment]
Looking for an answer to this too when you find time =D

An example CS2-SimpleAdmin.json would be great

**Comment by ddbmaster** [comment]
Yes, but I entered that it just doesn't work, see my entry
Or do I have to enter the workshop map differently


"DefaultMaps": [
"cs_italy",
"de_anubis",
"cs_office",
"de_inferno",
"de_dust2",
"de_mirage",
"de_vertigo",
"cs_italy"
  ],
  "WorkshopMaps": [
"fy_iceworld",
"de_losttemple"
  ],

an excerpt from the config for the maps Default maps only the workshop maps don't work.

That's why I'm asking for an example

**Comment by spTluxX** [comment]
wouldn't there be a possibilty to tell cs2-simpleadmin.json config to refer to "maplist.txt" which already has to be updated manually? 

"DefaultMaps": ["/%folder%/maplist.txt"]
"WorkshopMaps": ["/%folder%/maplist.txt"]

For workshop maps it would also maybe be a good thing if it was possible to refer to a map collection on steam workshop, that way the maplist for workshop maps would be updated automatically like this for example:

"WorkshopMaps": ["https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXXXXXXX"]

**Comment by ddbmaster** [comment]
So I've already tried
in CS2-SimpleAdmin.json
 "WorkshopMaps": [
  "3077769595//de_westwood_royal",
  "3070284539"//de_train
  ],
it does not work
"WorkshopMaps": [
  "3077769595""de_westwood_royal",
  "3070284539""de_train"
  ],
it does not work
"WorkshopMaps": [
  "3077769595":"de_westwood_royal",
  "3070284539":"de_train"
],
does not work too
Unfortunately, I don't know what to do next and I think that something else needs to be implemented in the code

**Comment by t4r1k58** [comment]
hi all

 my simpleadmin conf

"DefaultMaps": ["de_dust2",
    "cs_italy",
    "cs_office",
    "de_ancient",
    "de_anubis",
    "de_inferno",
    "de_mirage",
    "de_nuke",
    "de_overpass",
    "de_vertigo"],
  "WorkshopMaps": ["awp_lego_2",
    "awp_india",
	"awp_faction",
    "awp_arena",
	"awp_crazy_box_lego_zk",
    "pool",
    "fy_pool_day",
    "fy_iceworld",
    "aim_chill_zk",
    "aim_map",
    "aim_redline",
    "aim_headshot",
	"acs2_assault",
	"de_dust_classic",
    "$2000$_classics",
    "de_dust2_classic",
    "de_dust_hr"],

you create map collection and add workshop maps in this collection.
add your server.cfg host_workshop_collection "your collection id"

sorry my bad english. greetings from turkey

**Comment by ddbmaster** [comment]
Hello [t4r1k58](https://github.com/t4r1k58)

Very nice, it works wonderfully
Thanks alot

But I still wonder why it isn't in the description, so a lot of questions would already be answered

**Comment by daffyyyy** [comment]
Workshop maps fixed in https://github.com/daffyyyy/CS2-SimpleAdmin/releases/tag/build-222
