### ISSUE TITLE
Bind config

### ISSUE THREAD

**Issue by ToHold** [daffyyyy/CS2-SimpleAdmin#125]
Is that normal that bind KP_ENTER "say !admin" doesn't open admin panel wheras saying it by pressing Y and typing !admin works ?

**Comment by daffyyyy** [comment]
Its counterstrikesharp issue, u need to bind bind KEY css_admin

**Comment by ToHold** [comment]
Just for the other that's the same for selection would be :
bind KP_0 css_0
bind KP_1 css_1
bind KP_2 css_2
bind KP_3 css_3
bind KP_4 css_4
bind KP_5 css_5
bind KP_6 css_6
bind KP_7 css_7
bind KP_8 css_8
bind KP_9 css_9
