### ISSUE TITLE
workshop maps naming in the menu !admin

### ISSUE THREAD

**Issue by mayersgamer** [daffyyyy/CS2-SimpleAdmin#126]
![Screenshot 2024-06-07 090104](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/5068539/ff102429-fe27-42c0-8309-fcc6bdd7e94a)

how im supposed to know which ws maps are those ids , can i add the name of each map ?

**Comment by spTluxX** [comment]
Here my idea I posted in issue #123 could be a solution to the problem, too.

Quote: 

For workshop maps it would also maybe be a good thing if it was possible to refer to a map collection on steam workshop, that way the maplist for workshop maps would be updated automatically like this for example:

"WorkshopMaps": ["https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXXXXXXX"]

**Comment by mayersgamer** [comment]
> Here my idea I posted in issue #123 could be a solution to the problem, too.
> 
> Quote:
> 
> For workshop maps it would also maybe be a good thing if it was possible to refer to a map collection on steam workshop, that way the maplist for workshop maps would be updated automatically like this for example:
> 
> "WorkshopMaps": ["https://steamcommunity.com/sharedfiles/filedetails/?id=XXXXXXXXXX"]

hey wussup , its seem that they dont care about this issue.

i hate source 2 , amxmodx rules !! 😎🤙

**Comment by tf-anguskong** [comment]
maybe the workshop maps could be a tuple in the config file? I.E. It would look like this, I'm by NO means a developer but just an idea? The 2nd value being what's used in the admin UI in-game.

![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/48041768/192b4065-9214-4906-8c74-2deef132189c)

**Comment by ddbmaster** [comment]
It describes exactly how it works here
https://github.com/daffyyyy/CS2-SimpleAdmin/issues/123

And it works 100%

**Comment by mayersgamer** [comment]
bit i dont want to start the server with hostworkshopcollection , that will ruin default maps vote.
i hate valve for not providing a solution to vote maps that are a mix of ofc and ws maps .

**Comment by ddbmaster** [comment]
I can understand that, I feel the same way, but at least it's an option
and as long as nothing else comes from Valve, you can access it.

**Comment by daffyyyy** [comment]
Fixed in upcoming update

**Comment by daffyyyy** [comment]
Fixed in https://github.com/daffyyyy/CS2-SimpleAdmin/releases/tag/build-222
