### ISSUE TITLE
Permban

### ISSUE THREAD

**Issue by Sametyet53** [daffyyyy/CS2-SimpleAdmin#127]
Even though you have ban authority, it says you do not have permanent ban authority.

**Comment by Sametyet53** [comment]
Perm Ban Only Doesn't Work

**Comment by daffyyyy** [comment]
Add `@css/permban` flag

**Comment by Sametyet53** [comment]
![PROOYUN NET - Hizmet Kontrol Paneli - Google Chrome 9 06 2024 08_40_54](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/157792684/50b2e1c5-15a8-422c-b62b-4d253bb861b3)
Config file or Flag?
