### ISSUE TITLE
Not an issue but a question regarding Immunity.

### ISSUE THREAD

**Issue by Rii96** [daffyyyy/CS2-SimpleAdmin#139]
We have 3 groups of admin in our CFG file with immunity set to 50, 90 and 100.

Admins which have immunity set to 50 or 90 at /game/csgo/addons/counterstrikesharp/configs/admin_groups.json and /game/csgo/addons/counterstrikesharp/plugins/CS2-SimpleAdmin/data/admins.json are able to use commands on admins which have immunity at 100. Now I do not know what is the issue. 

My question is how can we fix that?

Thank you in advance.

**Comment by daffyyyy** [comment]
Normal commands or menu?

**Comment by Rii96** [comment]
Both. Menu, console commands and chat commands.

**Comment by daffyyyy** [comment]
Probably ur fault, on my server admin with immunity 80 cant kick me with immunity 100
