### ISSUE TITLE
[BUG?] css_unmute, css_ungag, css_unsilence

### ISSUE THREAD

**Issue by VaaLaaKi** [daffyyyy/CS2-SimpleAdmin#142]
Hello, I have experienced the following problems, as far as it is a problem and not on purpose(?):

For example, if someone's name is **"Jason"** then the unmute command works fine like this: **!unmute Jason**, but it doesn't work like this: **!unmute jason**

!unmute jason = Unmuted offline player with pattern jason.
!unmute Jason = Unmuted player Jason.

So you have to type the player's name perfectly, even the upper and lower case letters count.

I tested it with the player on the server the whole time, and if I don't type his name perfectly, the unmute doesn't work.

**Comment by daffyyyy** [comment]
Removing the penalties was never created with ONLINE players in mind.
Anything you type is looked up in the database - so you have to enter the exact player nickname or steamid
