### ISSUE TITLE
No map Menue ??

### ISSUE THREAD

**Issue by ddbmaster** [daffyyyy/CS2-SimpleAdmin#144]
You can no longer select maps in the menu, neither normal maps nor workshop maps
or will these now be integrated differently
 My map menu looked like this until now

My
CS2-SimpleAdmin.json
"Discord": {
    "DiscordLogWebhook": "",
    "DiscordPenaltyWebhook": ""
  },
  "DefaultMaps": [
    "cs_italy",
    "de_anubis",
    "cs_office",
    "de_inferno",
    "de_thera",
    "de_mirage",
    "de_vertigo",
    "de_mills",
    "cs_italy"
  ],
  "WorkshopMaps": [
    "de_piranesi",
    "Dune",
    "de_westwood_royal",
    "de_santo",
    "de_tides_cs2"
  ],
  "CustomServerCommands": [],

Has anything changed and if so, what or how can I change it?

**Comment by daffyyyy** [comment]
Read release description
https://github.com/daffyyyy/CS2-SimpleAdmin/releases/tag/build-222

**Comment by ddbmaster** [comment]
OKAY
But that doesn't work with the DefaultMaps

Thats OK
  "WorkshopMaps": {
    "de_piranesi" : null,
    "Dune" : null,
    "de_westwood_royal" : null,
    "de_santo" : null,
    "de_tides_cs2" : null
  },


Thats not OK
 "DefaultMaps": {
    "cs_italy" : null,
    "de_anubis" : null
 },
or
 "DefaultMaps": {
    "cs_italy" ,
    "de_anubis" :
 },

then the menu is empty

**Comment by daffyyyy** [comment]
Default maps not changed, 
I'll check soon

**Comment by ddbmaster** [comment]
Hmm  okay, I wait

But I find it strange that these no longer work

**Comment by ddbmaster** [comment]
Okay, I don't know but it's working now THANKS

Puhhhhhhh
