### ISSUE TITLE
admin menue

### ISSUE THREAD

**Issue by ddbmaster** [daffyyyy/CS2-SimpleAdmin#163]
Hello, I have a problem and I can no longer access the admin menu
the command for this is true 
css_admin
Can someone help me with this, thank you

**Comment by ddbmaster** [comment]
The Plugins is all Loadet and no menue 
[Client]   List of all plugins currently loaded by CounterStrikeSharp: 5 plugins loaded.
[Client]   [#1:LOADED]: "Welcome" (1.0) by Xenomoros
[Client]   [#2:LOADED]: "ShowPlayersInfo" (v1.3.0) by jockii (ch1nazes)
[Client]   [#3:LOADED]: "Get SteamID" (1.0.0) by Ganter1234
[Client]   [#4:LOADED]: "CS2 Parachute" (1.4) by Franc1sco Franug
[Client]   [#5:LOADED]: "CS2-SimpleAdmin (RELEASE)" (1.6.2a) by daffyy & Dliix66
[Client]     Simple admin plugin for Counter-Strike 2 :)

**Comment by daffyyyy** [comment]
![{EA3493FE-F16E-4219-B59E-3B15C8176780}](https://github.com/user-attachments/assets/92b56c7f-9e5f-4b28-a65f-474bae293c40)
