### ISSUE TITLE
css_silence not working sometimes

### ISSUE THREAD

**Issue by mayersgamer** [daffyyyy/CS2-SimpleAdmin#165]
css_silence not working sometimes , chat shows players is silenced but he keps talking .

only with this new version , older one works fine

**Comment by daffyyyy** [comment]
Change timezone

**Comment by mayersgamer** [comment]
timezone is utc in config , change it to what exactly ?

**Comment by daffyyyy** [comment]
use `Africa/Algiers` as timezone

**Comment by mayersgamer** [comment]
so i have set timezone to "Timezone": "Africa/Algiers", 

but silence doesnt work , mute and gag works
