### ISSUE TITLE
[QUESTION] How can I add a single flag "@css/vote" to a player without giving him "@css/generic" flag?

### ISSUE THREAD

**Issue by DearCrazyLeaf** [daffyyyy/CS2-SimpleAdmin#184]
My server has multiable warmpers streamers and sponsors, and I want they have vote permission , but when I added "@css/vote" flag to thire groups in admingroup.json, they still cannot run !vote, because they are missing the "@css/generic" flag.

Here is my groups settings : 

> "#css/warmper": {
	  "flags": [
	  "@css/warmper",
	  "@css/changemap",
	  "@css/vote"
	],
	"immunity": 10
  },
  "#css/streamer": {
	  "flags": [
	  "@css/streamer",
	  "@css/changemap",
	  "@css/vote"
	],
	"immunity": 10
  },
  "#css/sponsor": {
	  "flags": [
	  "@css/sponsor",
	  "@css/vote"
	],
	"immunity": 5
  }

**Comment by DearCrazyLeaf** [comment]
admin.json Example : 

> "1": {
    "identity": "123456789",
    "immunity": 10,
    "flags": [],
    "groups": [
	  "#css/streamer"
	],
    "command_overrides": {
      "css_plugins": true,
      "css": true
    }
  },
  "2": {
    "identity": "123456789",
    "immunity": 10,
    "flags": [],
    "groups": [
	  "#css/warmper"
	],
    "command_overrides": {
      "css_plugins": true,
      "css": true
    }
  },
  "3": {
    "identity": "123456789",
    "immunity": 10,
    "flags": [],
    "groups": [
	  "#css/sponsor"
	],
    "command_overrides": {
      "css_plugins": true,
      "css": true
    }
  }

**Comment by daffyyyy** [comment]
Try to add something like:
`{
    "#css/warmper": {
        "flags": [
            "@css/warmper",
            "@css/changemap",
            "@css/vote"
        ],
        "command_overrides": {
            "css_vote": true
        },
        "immunity": 10
    },
    "#css/streamer": {
        "flags": [
            "@css/streamer",
            "@css/changemap",
            "@css/vote"
        ],
        "command_overrides": {
            "css_vote": true
        },
        "immunity": 10
    },
    "#css/sponsor": {
        "flags": [
            "@css/sponsor",
            "@css/vote"
        ],
        "command_overrides": {
            "css_vote": true
        },
        "immunity": 5
    }
}`
Currently vote command use @css/generic flag but its dangerous to give it not to admin.
You need to override command permission, probably i change default permission to @css/vote in next update

**Comment by DearCrazyLeaf** [comment]
Ok it works now, thanks.
