### ISSUE TITLE
Changed Maps

### ISSUE THREAD

**Issue by gha241** [daffyyyy/CS2-SimpleAdmin#185]
when I change maps via the admin panel, the server crashes

**Comment by gha241** [comment]
"DefaultMaps": ["de_dust2","de_mirage","de_inferno"],
	"WorkshopMaps":{},

**Comment by crashzk** [comment]
GOTV enabled?

In my tests I noticed that if GOTV is enabled on the server the server always crashes, as mentioned. Something related to `tv_record`.

![image](https://github.com/user-attachments/assets/30a08198-8a98-418d-9a5b-748575c8a841)

As you can see, they suggested I test a delay in changing the map, time to first execute the `tv_stoprecord` command and delay to then change the map.

Would something like this be possible in the plugin @daffyyyy?

**Comment by daffyyyy** [comment]
Not simpleadmin issue, just disable gotv or use plugin to stop record on end of map
