### ISSUE TITLE
[REQ] Option to configure `DiscordLogWebhook` for each penalty

### ISSUE THREAD

**Issue by crashzk** [daffyyyy/CS2-SimpleAdmin#190]
This way we can configure more than one channel to send webhooks and leave each penalty separated by channel.

**Comment by daffyyyy** [comment]
?? XD First use plugin then send feature request...
Now you can set diff webhook for each penalty, logwebhook used only for commands logs

**Comment by crashzk** [comment]
Outdated file... :)

Generate a new one here and test, sorry.
