### ISSUE TITLE
[REQ] Support for `maps.txt` for map switching commands

### ISSUE THREAD

**Issue by crashzk** [daffyyyy/CS2-SimpleAdmin#2]
Would it be possible to implement so that the `css_map` and `css_wsmap` commands change the map to just what is in this file?

So I believe that if we don't change the map manually using one of these commands, it will follow the map rotation of this file, that is, if I have this list of maps in the file:
```
de_mirage
de_inferno
de_dust2
de_anubis
```
The server will just keep switching to this maps.

**Comment by daffyyyy** [comment]
Its server manage plugin, not map rotating :D
