### ISSUE TITLE
simple admin 

### ISSUE THREAD

**Issue by Matthews02** [daffyyyy/CS2-SimpleAdmin#22]
can you advise me, I put all the files from the folder into plugins sharp
in the configuration between quotation marks he added the database data
and what else how to set in cfg admin.example.json?

**Comment by daffyyyy** [comment]
Rename `admins.example.json` to `admins.json` and configure.
https://docs.cssharp.dev/docs/admin-framework/defining-admins.html

**Comment by Matthews02** [comment]
I have to connect to the database and, if so, to which folder
and then what is the command to execute the rights

**Comment by Matthews02** [comment]
and now that I'm like this, do I have root rights?

**Comment by Matthews02** [comment]
{
  "Matthews": {
    "identity": "76561198299893462",
    "flags": ["@css/root"]
  },
  "another ZoNiCaL": {
    "identity": "STEAM_0:1:1",
    "flags": ["@css/generic"]
  }
}

**Comment by Matthews02** [comment]
and how should I enter chhat otherwise slay ban kick

**Comment by Matthews02** [comment]
and how will you answer everything if you describe to me how to add maps to cs2
it's completely different from csgo, I don't know what to do anymore

**Comment by Matthews02** [comment]
??
