### ISSUE TITLE
a few suggestions

### ISSUE THREAD

**Issue by Waterovsky** [daffyyyy/CS2-SimpleAdmin#24]
Hi. I have a few suggestions... (I'm using v1.2.4b)

1. Could you expand the ban/mute reason to more than one word?
    
    Example: "!addban xxx 0 Inappropriate language"
    Currently, the reason appears as 'Inappropriate'. Not 'Inappropriate language'.

2. It seems that adding an administrator permanently doesn't work. Could you add/fix this functionality?

3. A server identification feature would be useful. For instance, new database columns containing server ID.

**Comment by asdfxD** [comment]
can you guys add css_resize "resize players"

**Comment by Waterovsky** [comment]
Found the reason why adding an admin permanently doesn't work.

The error occurs when creating the table sa_admins _(CREATE TABLE IF NOT EXISTS 'sa_admins')_
**At the moment, it looks like this:** 
'ends' timestamp,
**It should be:** 
'ends' timestamp NULL,

You can also correct the typo in 'lang/pl.json':
"sa_admin_umfreeze_message" to "sa_admin_unfreeze_message"

**Comment by daffyyyy** [comment]
For 1
U can use "My reason" same as in sourcemod

**Comment by daffyyyy** [comment]
Probably done
