### ISSUE TITLE
Problem with understanding syntax

### ISSUE THREAD

**Issue by lostsoul6** [daffyyyy/CS2-SimpleAdmin#26]
Hello daffyyyy

I'm new to running cs servers . I installed your plugin and I'm trying to add myself as admin but I don't know the syntax . No matter what I enter I get a message saying invalid player .

steam id : "7656119XXX2928055"
name : "vicious attacker"

I have 2 css admin groups . one is admin and the other one moderator : 

```
{
  "#css/admin": {
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ],
    "immunity": 100
  }
   "#css/moderator": {
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/slay",
      "@css/changemap",
      "@css/chat",
      "@css/vote",
    ],
    "immunity": 100
  }
}
```

what should I enter on console to add myself as admin ?

Regards ,

**Comment by lostsoul6** [comment]
update : 

I was able to add admin but when in server , I can't run !admin . it says I'm missing correct permissions .

I attach screenshot of error and phpmyadmin . can you please help ? @daffyyyy 

![admin-issue](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/127633547/73e19282-ae9e-4ad8-9655-0c9d7a3e9927)
![phpadmin](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/127633547/d813c891-4914-45b1-b632-c93efa2539a5)

counterstrikesharp admin.json :  

```
{
  "M-----e": {
    "identity": "765611XXXXX65731",
    "immunity": 100,
    "flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root"
    ],
    "groups": [
      "#css/admin"
    ],
    "command_overrides": {
      "css_plugins": true,
      "css": true
    }
  },
  "Another erikj": {
    "identity": "STEAM_0:1:1",
    "flags": ["@mycustomplugin/admin"]
  }
}
```

Regards ,

**Comment by daffyyyy** [comment]
Its steam/css isue for now.
Need to wait

**Comment by lostsoul6** [comment]
> Its steam/css isue for now. Need to wait

Have they announced it anywhere? or any date for fix?
