### ISSUE TITLE
[suggestion] silent commands

### ISSUE THREAD

**Issue by KerchooKult** [daffyyyy/CS2-SimpleAdmin#30]
allow commands like kick gag mute ban to be executed silently without broadcasting in chat with an additional permission

**Comment by daffyyyy** [comment]
Try latest build, `css_silentmode` command

**Comment by KerchooKult** [comment]
Awesome! Do you think you could make it a separate flag instead of kick? I don't want mods to have it.

**Comment by daffyyyy** [comment]
> Awesome! Do you think you could make it a separate flag instead of kick? I don't want mods to have it.

U can use command override system from counterstrieksharp 
https://docs.cssharp.dev/docs/admin-framework/defining-command-overrides.html

**Comment by BrutalCSEjziponken** [comment]
Shouldnt css_silentmode be like a config setting? Rather than a command all admins can run on each server? :P
