### ISSUE TITLE
[feature request] Add this useful commands pls

### ISSUE THREAD

**Issue by criskkky** [daffyyyy/CS2-SimpleAdmin#32]
Hi @daffyyyy,
Could you add this commands? pls 🙏
(requires review to see which ones are doable, I hope all).

**Feature request:**

- **Add new commands:**
  - `!rr / !restartround [seconds]` - Restarts the round in x seconds, without resetting the match's stats. Use `!rr 0` to stop restart from happening. Default first argument 1.
  - `!rg / !restartgame [seconds]` - Restarts the round & game in x seconds, while also resetting the match's stats. Use `!rg 0` to stop restart from happening. Default first argument 1.
  - `!1up / !hrevive <#userid|name|steamid|targetid>` - Respawns a player in his last known death position.
  - `!xyz` - Prints your position in-game. [could help some devs]
  - `!bring <#userid|name|steamid|targetid>` - Teleports a player to your aim.
  - `!goto <#userid|name|steamid>` - Teleports yourself to a player's position using stuck rules to ensure you never get stuck inside the player. Experimental command which may be bugged until tested completely.
  - `!heal / !hp <#userid|name|steamid|targetid> [health] [armor] [helmet=1/0]` - Sets a player's health, armor, or helmet. Using x or anything not a number will ignore and using "max" in health will set to the player's max health ( usually 100 but some servers may change )
  - `!strip <#userid|name|steamid|targetid>` - Removes all weapons from a player, except knife and bomb.
  - `!disarm <#userid|name|steamid|targetid>` - Removes all weapons from a player, including knife and bomb.
  - `!exec <#userid|name|steamid|targetid> <command>` - Forces a client to execute commands.
  - `!god <#userid|name|steamid|targetid>` - Makes a player immune to damage.
  - `!noclip <#userid|name|steamid|targetid>` - Set player noclip.
  - `!respawn <#userid|name|steamid|targetid>` - Respawn player.
  - `!cc / !clear` - Clears the chat.
  - `!team <#userid|name|steamid|targetid> <T/CT/SPEC>` - Set player team.
  - `!swap <#userid|name|steamid|targetid>` - Transfer player to the opposite team.

**Comment by Kamii193** [comment]
@criskkky  bro did it work for u ??? i didnt work for me help me out i can give u my discord

**Comment by criskkky** [comment]
sure @Kamii193 np

**Comment by KewaiiGamer** [comment]
!swap is missing. 
!1up / !hrevive is missing
!xyz is missing
!respawn was implemented with !1up /!hrevive logic
!disarm is missing
!exec is missing
!restartgame and !restartround are basically the same command
!heal only exists as !hp. add aliases css_heal and css_health by default
