### ISSUE TITLE
how i do it ?

### ISSUE THREAD

**Issue by Kamii193** [daffyyyy/CS2-SimpleAdmin#37]
what i change in this folder ?? 
u said i need to configure plugin in addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin/CS2-SimpleAdmin.json

// This configuration was automatically generated by CounterStrikeSharp for plugin 'CS2-SimpleAdmin', at 2024/01/22 02:00:43
{
  "Version": 2,
  "DatabaseHost": "",
  "DatabasePort": 3876,
  "DatabaseUser": "",
  "DatabasePassword": "",
  "DatabaseName": "",
  "KickTime": 10,
  "DisableDangerousCommands": true,
  "ConfigVersion": 2
}
i have no idea what i do here !

**Comment by lostsoul6** [comment]
@Kamii193 

You must enter your database information . have you set up mysql database for your server?

**Comment by Kamii193** [comment]
@lostsoul6 No not yet , im finding it so haaard , my head is turning around 
it syas i need mysql and to host i need xmpp (its free) so youtube is planty with it but im not sure what im loking for 
i installed mysql and thats it 
IM LOST !

**Comment by lostsoul6** [comment]
@Kamii193 , first using ssh you need to set mysql root password . after that if you have troubles working with mysql in command line , you can install phpmyadmin and manage your database and users with phpmyadmin .

**Comment by daffyyyy** [comment]
utf8mb4_general_ci
