### ISSUE TITLE
How can I change the permissions required for running a command?

### ISSUE THREAD

**Issue by lostsoul6** [daffyyyy/CS2-SimpleAdmin#38]
Hello @daffyyyy ,

Is it possible to define what permissions are required to run a command based on our need?

- css_hp <#userid or name> [health] - Set player health // @css/slay
- css_speed <#userid or name> [speed] - Set player speed // @css/slay

for example I saw the documentation and you said the default permission required to run these commands is @css/slay however I want it to be @css/cheats .

It would be a good idea if you can include options in config file to enable and disable each command by true and false and then define the permissions for each one based on our setup .

**Comment by daffyyyy** [comment]
Use counterstrikesharp commands override

**Comment by lostsoul6** [comment]
can you help me with a sample syntax ? I checked css documents and tried a few different combos but still an admin with slay permission can do it .

**Comment by lostsoul6** [comment]
my problem was that I didn't restart the server after changing the css files . problem solved with restart .
