### ISSUE TITLE
[REQ] MySQL Support | Commands to add and remove admin

### ISSUE THREAD

**Issue by crashzk** [daffyyyy/CS2-SimpleAdmin#5]
It would be interesting to implement MySQL support along with commands to add and remove admins.

- `css_addadmin <admin_name> <steamid64> <duration(minutes)/0 (permanent)> <flags/admin groups> <immunity>` - Add an administrator
- `css_deleteadmin <steamid64>` - Delete an administrator

In my tests, the plugin currently uses the CSSharp admin system, it would be interesting to leave it in case of adding new admins directly through the CSSharp admin file, but a MySQL database with support for adding and removing admins through the console, so we can synchronize admins across multiple servers, making it easier for those who have multiple servers.

**Comment by mrdiega** [comment]
+1

**Comment by daffyyyy** [comment]
Done

**Comment by crashzk** [comment]
@crashzk thanks.  Doubts regarding editing the group/flag, immunity of a player, do we use the same command to add?

Or would some update command be better for this issue?

 For now I believe the solution would be to delete the player and add it again.
