### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by holzfuss** [daffyyyy/CS2-SimpleAdmin#61]
After first launch, u need to configure plugin in addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin/CS2-SimpleAdmin.json

This config file is not created.
No useful link how to fill this file.

How to use mysql?

css_hide will crah server for me.

**Comment by ddbmaster** [comment]
For me this file is addons/counterstrikesharp/configs/plugins/CS2-SimpleAdmin/CS2-SimpleAdmin.json

also not created

and where do I enter my SQL data

Sorry for my English
is via Google Translator

Please Help me

**Comment by daffyyyy** [comment]
Update css

**Comment by ddbmaster** [comment]
???? !!!!
waiting for an update from CS2-SimpleAdmin
Or how should I understand that
