### ISSUE TITLE
No json file is created in configs/plugins

### ISSUE THREAD

**Issue by crywolfy** [daffyyyy/CS2-SimpleAdmin#63]
Hi there, i installed the plugin on my cs2 server, at meta list is loaded but the .json for db does not appear, also missing a lot of info from plugin instalation like were do the .cs files go? 

Debian 12

EDIT: Nvm succeded
BUG, css_god doesn't work, basicaly does nothing.

**Comment by daffyyyy** [comment]
Update plugin
