### ISSUE TITLE
Error with panel, can't edit cs2 server things

### ISSUE THREAD

**Issue by Kl4rkx** [daffyyyy/CS2-SimpleAdmin#64]
### **Error with panel, can't edit cs2 server things**

Since I changed the domain of the server now I can't change from the panel anything that has to do with the cs2 server, basically the "manage servers" does not work and I get this in the panel console

![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/90530426/55b46a4d-24cb-4a34-b9c2-dbbec4b7dbfd)

![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/90530426/0fef2b68-1163-4927-9f16-3b4eb78d4ebb)

**PANEL:**
![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/90530426/3f60e654-5c0e-4d99-be4a-4953a8d0637c)
AND
![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/90530426/7538707a-a845-40da-8511-6b8e00f7298c)

MANAGING BANS AND MUTES DOES NOT WORK

**Comment by daffyyyy** [comment]
Not here
