### ISSUE TITLE
Adminsimple + sharptimer

### ISSUE THREAD

**Issue by Prull99** [daffyyyy/CS2-SimpleAdmin#71]
Hi. When i use this plugin with sharptimer after that nobody can use the !tp command on the kz server. Can you fix it please?

**Comment by finlayd** [comment]
Bump. Happening with me aswell

**Comment by finlayd** [comment]
https://github.com/finlayd/CS2-SimpleAdmin-SharpTimer-FIx

made a fork that removes the !tp command as a quick fix
