### ISSUE TITLE
When user is gagged chat commands cannot be used

### ISSUE THREAD

**Issue by shmitzas** [daffyyyy/CS2-SimpleAdmin#76]
When a user is gagged they cannot perform chat commands that start with ! or / prefixes (defined in CSS core.json)

**Comment by VortDyn** [comment]
I agree, this should be fixed

**Comment by daffyyyy** [comment]
Temp fixed in next release

**Comment by shmitzas** [comment]
Re-opening as this is not fixed in the newest build (215)

**Comment by daffyyyy** [comment]
Probably fixed in next build
