### ISSUE TITLE
Noclip/Freeze bugs

### ISSUE THREAD

**Issue by asdfxD** [daffyyyy/CS2-SimpleAdmin#8]
when using noclip it feels laggy, doesn't know from other plugins.

after unfreeze, players legs are sliding on the ground, jumping feels laggy.

when i die as admin and respawn myself, it does not work. 

(Admin) asdfxD respawned asdfxD!

but i'm still dead.

**Comment by DEADLYDEVIL-IR** [comment]
You must be once alive to be respawned
