### ISSUE TITLE
[Bug] ServerID Database

### ISSUE THREAD

**Issue by VortDyn** [daffyyyy/CS2-SimpleAdmin#83]
If you change the name on the server, the database will try to add the same server, but already with a buggy IP, new name
![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/54004093/52607acb-d69d-4067-90df-54c651d2546b)
Is that also why the admin area is crashing?
![image](https://github.com/daffyyyy/CS2-SimpleAdmin/assets/54004093/e77fa7a8-99b5-420d-9a73-89f93b63d649)
First null ► serverID

**Comment by daffyyyy** [comment]
Known bug with `hostip` i guess cant be fixed now
