### ISSUE TITLE
how to pause or unload a plugin

### ISSUE THREAD

**Issue by mayersgamer** [daffyyyy/CS2-SimpleAdmin#89]
css_plugins list

[Client]   List of all plugins currently loaded by CounterStrikeSharp: 7 plugins loaded.
[Client]   [#1:LOADED]: "Anti Team Flash" (0.0.3.1b) by Franc1sco Franug
[Client]   [#2:LOADED]: "ResetScore" (1.0.6) by StefanX
[Client]   [#3:LOADED]: "Weapon Restrict" (1.2.1) by Quake1011
[Client]     Prohibits purchase or picking up restricted weapons
[Client]   [#4:LOADED]: "Advertisement" (v1.0.6) by thesamefabius
[Client]   [#5:LOADED]: "AFK Manager" (0.1.1) by NiGHT & K4ryuu
[Client]   [#6:LOADED]: "CS2-SimpleAdmin" (1.3.6c) by daffyy & Dliix66
[Client]     Simple admin plugin for Counter-Strike 2 :)
[Client]   [#7:LOADED]: "WeaponPaints" (1.9b) by Nereziel & daffyy
[Client]     Skin, gloves and knife selector, standalone and web-based

css_plugins unload #3

[Client] Could not unload plugin "#3"

i want to pause this plugin to play some awp maps . awp is restricted by default with this plugin.

**Comment by OhGodANoob** [comment]
Try without the #

`css_plugins stop/unload 3`

**Comment by daffyyyy** [comment]
whu u ask here about weapon restrict?
