### ISSUE TITLE
adding maps to menu

### ISSUE THREAD

**Issue by blackoutptPT** [daffyyyy/CS2-SimpleAdmin#90]
I cannot add maps to menu. Can you explain how?

**Comment by t4r1k58** [comment]
hi my config this working

 },
  "DefaultMaps": ["de_dust2",
    "ar_shoots",
    "ar_baggage",
    "cs_italy",
    "cs_office",
    "de_ancient",
    "de_anubis",
    "de_inferno",
    "de_mirage",
    "de_nuke",
    "de_overpass",
    "de_vertigo"],
  "WorkshopMaps": ["awp_lego_2",
    "awp_lego_2011",
    "awp_india",
    "pool",
    "fy_pool_day",
    "fy_iceworld_y0",
    "awp_crazy_box_lego_zk",
    "aim_chill_zk",
    "de_dust_classic",
    "$2000$_classics",
    "de_dust2_classic",
    "aim_map",
    "aim_redline",
    "dust2longfixed",
    "de_dust_hr",
    "fy_iceworld"],
  "CustomServerCommands": []
}
